# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "registry.gitlab.com/hirschenberger/pylon:rustup-all"

job:
  tags:
    - docker


# Use cargo to test the project
test:
    cargo:
        script:
            - rustc --version && cargo --version
            - cd pylon-sys
            - cargo test --all --verbose
            - cd ../pylon
            - cargo test --all --verbose
