image: "registry.gitlab.com/hirschenberger/pylon:rustup-all"

before_script:
    - source /opt/pylon5/bin/pylon-setup-env.sh /opt/pylon5
    - rustc --version && cargo --version
    - export LD_LIBRARY_PATH=/opt/pylon5/lib64


pylon-sys:
    script:
    - cd pylon-sys
    - cargo test --all --verbose
    
pylon:
    script:
    - cd pylon
    - cargo test --all --verbose
