image: "registry.gitlab.com/hirschenberger/pylon:rustup-all"

#job:
#    tags:
#    - docker

# Use cargo to test the project
cargo:
    script:
    - rustc --version && cargo --version
    - cd pylon-sys
    - cargo test --all --verbose
    - cd ../pylon
    - cargo test --all --verbose
