[package]
name = "pylon-sys"
version = "0.1.0"
authors = ["Falco Hirschenberger <falco.hirschenberger@gmail.com>"]
license = "MIT"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.49"
