[package]
name = "pylon"
version = "0.1.0"
authors = ["Falco Hirschenberger <falco.hirschenberger@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
pylon-sys = {version = "0.1", path = "../pylon-sys"}
image = "0.21"
